
name: ch

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Move and Rename Binaries for Compatibility
      #   run: |
      #     echo "Restructuring directories for compatibility..."
      #     mkdir -p vendor
          
      #     # Move xray executable to the correct location and name
      #     mv xray/xray vendor/xray_linux
          
      #     # Move hysteria executable to the correct location and name
      #     mv hy2/hysteria vendor/hysteria_linux
          
      #     echo "Successfully moved and renamed binaries. Final structure of 'vendor' directory:"
      #     ls -l vendor
      # - name: Set Execute Permissions
      #   run: |
      #     chmod +x vendor/xray_linux
      #     chmod +x vendor/hysteria_linux
      #     echo "Execute permissions set on binaries."
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set weekly cache key
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: pip-cache-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ env.cache_id }} # کلید بهتر برای کش
          path: ~/.cache/pip
          restore-keys: |
            pip-cache-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies
        run: pip install -r requirements.txt
        # run: pip install -r requirements.txt


      - name: Run checker script
        run: python cl.py

      - name: Commit and Push changes
        run: |
          FILE1="final.txt"

          if [[ -n $(git status --porcelain $FILE1) ]]; then
            echo "Changes detected in $FILE1. Committing..."

            git add $FILE1

            git commit -m "chore: Update results ($FILE1) [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes detected in $FILE1. Nothing to commit."
          fi