name: without-timer

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Move and Rename Binaries for Compatibility
        run: |
          echo "Restructuring directories for compatibility..."
          mkdir -p vendor
          
          # Move xray executable to the correct location and name
          mv xray/xray vendor/xray_linux
          
          # Move hysteria executable to the correct location and name
          mv hy2/hysteria vendor/hysteria_linux
          
          echo "Successfully moved and renamed binaries. Final structure of 'vendor' directory:"
          ls -l vendor
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # استفاده از نسخه مشخص بهتر است

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: pip-cache-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-cache-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ----- مرحله Set execute permissions حذف شد -----
      # کتابخانه python_v2ray خودش این کار را انجام می‌دهد.

      - name: Run checker script
        # !!! مطمئن شوید که دارید اسکریپت جدید را اجرا می‌کنید !!!
        run: python cl.py

      - name: Commit and Push changes
        run: |
          FILE1="final.txt"
          if [[ -n $(git status --porcelain $FILE1) ]]; then
            echo "Changes detected in $FILE1. Committing..."
            git add $FILE1
            git commit -m "chore: Update results ($FILE1) [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes detected in $FILE1. Nothing to commit."
          fi
